export enum UserRole {
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  LIBRARIAN = 'LIBRARIAN',
  ADMIN = 'ADMIN',
}

export enum ItemStatus {
  AVAILABLE = 'AVAILABLE',
  BORROWED = 'BORROWED',
  RESERVED = 'RESERVED',
  LOST = 'LOST',
  DAMAGED = 'DAMAGED',
}

export enum Genre {
  FICTION = 'FICTION',
  NON_FICTION = 'NON_FICTION',
  SCIENCE = 'SCIENCE',
  HISTORY = 'HISTORY',
  TECHNOLOGY = 'TECHNOLOGY',
  ART = 'ART',
  OTHER = 'OTHER',
}

export enum ActivityType {
  LOAN_CREATED = 'LOAN_CREATED',
  LOAN_RETURNED = 'LOAN_RETURNED',
  LOAN_RENEWED = 'LOAN_RENEWED',
  RESERVATION_PLACED = 'RESERVATION_PLACED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  FINE_APPLIED = 'FINE_APPLIED',
  FINE_PAID = 'FINE_PAID',
  FINE_WAIVED = 'FINE_WAIVED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_ACTIVATED = 'USER_ACTIVATED',
}

